version: 1
autoUpdate: true
lanugage: en_US
# Mobtypes which can be picked up
allowedMobTypes:
  - CHICKEN
  - WOLF
  - RABBIT
# Active worlds
worlds:
  - world
# Use worlds as blacklist instead of whitelist
blacklist: false
# Allows to pickup a entitiy which carries an entity
allowStacking: false
# The force multiplier which is used when a mob is thrown.
throwForce: 1.5
